#!/usr/bin/env python3
"""
mini_fshgen.py
==============

Experimental BAT-focused Python subset of memo33/fshgen.

Implemented:
- Wavefront OBJ -> SimCity 4 S3D v1.5
- PNG/BMP -> single-image FSH using DXT1
- IID extraction from filenames
- DBPF 1.0 / .SC4Model writing
- QFS/RefPack compression + DIR resource generation

Not implemented:
- export
- DXT3/DXT5
- mipmaps
- slicing/layer composition
- separate alpha files
- darken/brighten
- QFS/RefPack compression
- append mode
- general-purpose OBJ features beyond triangulated v/vt faces

DBPF resources are QFS/RefPack-compressed when compression saves enough space.
A standard DBPF DIR resource is generated automatically for compressed entries.

This is a BAT-only prototype, not a drop-in replacement for all fshgen features.
"""

from __future__ import annotations

import argparse
import glob
import re
import struct
import sys
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Sequence

from PIL import Image


TID_S3D = 0x5AD0E817
TID_FSH = 0x7AB50E44

TID_DIR = 0xE86B1EEF
GID_DIR = 0xE86B1EEF
IID_DIR = 0x286B1F03
QFS_MAGIC = 0xFB10

VERT_FORMAT = 0x80004001
INDX_STRIDE = 2

PRIM_TRIANGLE = 0

MATS_ALPHA_TEST = 1 << 0
MATS_DEPTH_TEST = 1 << 1
MATS_BACKFACE_CULLING = 1 << 3
MATS_TEXTURING = 1 << 5

MATS_FUNC_GREATER = 4
MATS_FUNC_LESS_EQUAL = 3

MATS_BLEND_ZERO = 0
MATS_BLEND_ONE = 1

WRAP_REPEAT = 3
MAG_NEAREST = 0
MIN_NEAREST_NO_MIPMAP = 0

PLAYMODE_LOOPING = 3


# ---------------------------------------------------------------------------
# Binary helpers
# ---------------------------------------------------------------------------

def u16(v: int) -> bytes:
    return struct.pack("<H", v & 0xFFFF)


def i16(v: int) -> bytes:
    return struct.pack("<h", v)


def u32(v: int) -> bytes:
    return struct.pack("<I", v & 0xFFFFFFFF)


def f32(v: float) -> bytes:
    return struct.pack("<f", float(v))


def named_string(name: str | None, *, short: bool = False) -> bytes:
    """
    S3D string form used by scdbpf:
    - ordinary strings: one-byte length including trailing NUL
    - ANIM names: two-byte short length
    """
    if not name:
        return b"\x00\x00" if short else b"\x00"

    raw = name.encode("ascii", errors="replace")[:254]
    if short:
        return bytes((len(raw) + 1, 0)) + raw + b"\x00"
    return bytes((len(raw) + 1,)) + raw + b"\x00"


# ---------------------------------------------------------------------------
# Filename / glob handling
# ---------------------------------------------------------------------------

_ID_RE = re.compile(
    r"(?i)(?<![-0-9a-f])(?:0x)?([0-9a-f]{8}|0)(?=[_ .])"
)


def extract_last_iid(filename: str) -> int:
    """
    Extract the last absolute hexadecimal ID from a filename.

    The current BAT generator uses names such as:
      5ad0e817_ffffffff_00030000.obj
      00030000_Day.png
    """
    matches = list(_ID_RE.finditer(Path(filename).name))
    if not matches:
        raise ValueError(f"no hexadecimal IID found in filename: {filename}")
    return int(matches[-1].group(1), 16)


def expand_inputs(items: Sequence[str]) -> list[Path]:
    """
    Expand quoted wildcard arguments internally.

    This is convenient when invoked from subprocess without shell expansion:
      'output/*.obj'
      'output/*_Day.png'
    """
    result: list[Path] = []

    for item in items:
        if any(ch in item for ch in "*?["):
            found = sorted(Path(p) for p in glob.glob(item))
            if not found:
                print(
                    f"warning: pattern matched no files: {item}",
                    file=sys.stderr,
                )
            result.extend(found)
        else:
            result.append(Path(item))

    return result


# ---------------------------------------------------------------------------
# Minimal OBJ parser
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class ObjRef:
    vertex: int
    texcoord: int


@dataclass
class ObjMesh:
    material: str
    object_name: str | None
    faces: list[tuple[ObjRef, ObjRef, ObjRef]] = field(default_factory=list)


@dataclass
class ObjModel:
    vertices: list[tuple[float, float, float]]
    texcoords: list[tuple[float, float]]
    meshes: list[ObjMesh]


def resolve_obj_index(text: str, count: int) -> int:
    idx = int(text)

    if idx == 0:
        raise ValueError("OBJ indices are 1-based; index 0 is invalid")

    if idx > 0:
        return idx - 1

    return count + idx


def parse_obj(path: Path) -> ObjModel:
    """
    Parse the limited OBJ dialect generated by the BAT script.

    Supported:
    - v
    - vt
    - o
    - g
    - usemtl
    - triangular f entries containing v/vt or v/vt/vn

    Normals are ignored. Vertices are later reindexed by (v, vt), matching the
    behavior needed for the generated BAT OBJ files.
    """
    vertices: list[tuple[float, float, float]] = []
    texcoords: list[tuple[float, float]] = []
    meshes: list[ObjMesh] = []

    object_name: str | None = None
    current_material = ""
    current_mesh: ObjMesh | None = None

    def ensure_mesh() -> ObjMesh:
        nonlocal current_mesh

        if current_mesh is None:
            current_mesh = ObjMesh(
                material=current_material,
                object_name=object_name,
            )
            meshes.append(current_mesh)

        return current_mesh

    lines = path.read_text(
        encoding="utf-8",
        errors="replace",
    ).splitlines()

    for lineno, line in enumerate(lines, 1):
        line = line.strip()

        if not line or line.startswith("#"):
            continue

        parts = line.split()
        op = parts[0]

        if op == "v":
            if len(parts) < 4:
                raise ValueError(
                    f"{path}:{lineno}: malformed vertex"
                )

            vertices.append(
                (
                    float(parts[1]),
                    float(parts[2]),
                    float(parts[3]),
                )
            )

        elif op == "vt":
            if len(parts) < 3:
                raise ValueError(
                    f"{path}:{lineno}: malformed texture coordinate"
                )

            texcoords.append(
                (
                    float(parts[1]),
                    float(parts[2]),
                )
            )

        elif op == "o":
            object_name = (
                " ".join(parts[1:])
                if len(parts) > 1
                else None
            )
            current_mesh = None

        elif op == "g":
            # The BAT generator writes both o and g.
            # Object names are sufficient for the S3D ANIM name.
            continue

        elif op == "usemtl":
            current_material = (
                " ".join(parts[1:])
                if len(parts) > 1
                else ""
            )
            current_mesh = None

        elif op == "f":
            refs: list[ObjRef] = []

            for token in parts[1:]:
                bits = token.split("/")

                if (
                    len(bits) < 2
                    or not bits[0]
                    or not bits[1]
                ):
                    raise ValueError(
                        f"{path}:{lineno}: every face vertex "
                        "must contain v/vt"
                    )

                vi = resolve_obj_index(
                    bits[0],
                    len(vertices),
                )
                ti = resolve_obj_index(
                    bits[1],
                    len(texcoords),
                )

                refs.append(
                    ObjRef(
                        vertex=vi,
                        texcoord=ti,
                    )
                )

            if len(refs) != 3:
                raise ValueError(
                    f"{path}:{lineno}: only triangulated faces "
                    f"are supported; got {len(refs)} vertices"
                )

            ensure_mesh().faces.append(
                (
                    refs[0],
                    refs[1],
                    refs[2],
                )
            )

        elif op in (
            "vn",
            "s",
            "mtllib",
        ):
            continue

        else:
            # Ignore comments / metadata unknown to this minimal parser.
            continue

    meshes = [
        mesh
        for mesh in meshes
        if mesh.faces
    ]

    if not vertices:
        raise ValueError(
            f"{path}: OBJ has no vertices"
        )

    if not texcoords:
        raise ValueError(
            f"{path}: OBJ has no texture coordinates"
        )

    if not meshes:
        raise ValueError(
            f"{path}: OBJ has no triangle meshes"
        )

    return ObjModel(
        vertices=vertices,
        texcoords=texcoords,
        meshes=meshes,
    )


# ---------------------------------------------------------------------------
# OBJ -> S3D
# ---------------------------------------------------------------------------

def material_iid(base_iid: int, index: int) -> int:
    """
    BAT material/tile IID mapping.

    Supports up to 1024 materials, matching the bit allocation used by the BAT
    model convention.
    """
    if not 0 <= index < 1024:
        raise ValueError(
            "S3D model must have fewer than 1024 materials"
        )

    offset = (
        ((index & 0x0380) << 5)
        | ((index & 0x0040) << 5)
        | ((index & 0x0030) << 2)
        | (index & 0x000F)
    )

    return (base_iid + offset) & 0xFFFFFFFF


@dataclass
class S3dMesh:
    name: str | None
    material_name: str | None
    material_iid: int
    vertices: list[tuple[float, float, float, float, float]]
    indices: list[int]


def convert_obj_meshes(
    model: ObjModel,
    base_iid: int,
) -> list[S3dMesh]:
    result: list[S3dMesh] = []

    for mesh_index, mesh in enumerate(model.meshes):
        refs: list[ObjRef] = []
        lookup: dict[ObjRef, int] = {}

        for face in mesh.faces:
            for ref in face:
                if ref not in lookup:
                    lookup[ref] = len(refs)
                    refs.append(ref)

        verts: list[
            tuple[float, float, float, float, float]
        ] = []

        for ref in refs:
            x, y, z = model.vertices[ref.vertex]
            tex_u, tex_v = model.texcoords[ref.texcoord]

            # Default fshgen OBJ conversion reverses V.
            verts.append(
                (
                    x,
                    y,
                    z,
                    tex_u,
                    1.0 - tex_v,
                )
            )

        indices: list[int] = []

        for face in mesh.faces:
            indices.extend(
                lookup[ref]
                for ref in face
            )

        if len(verts) > 0xFFFF:
            raise ValueError(
                "S3D vertex group exceeds 65535 vertices"
            )

        if len(indices) > 0xFFFF:
            raise ValueError(
                "S3D index group exceeds 65535 indices"
            )

        result.append(
            S3dMesh(
                name=mesh.object_name,
                material_name=mesh.material or None,
                material_iid=material_iid(
                    base_iid,
                    mesh_index,
                ),
                vertices=verts,
                indices=indices,
            )
        )

    return result


def encode_vert_group(mesh: S3dMesh) -> bytes:
    out = bytearray()

    out += u16(0)
    out += u16(len(mesh.vertices))
    out += u32(VERT_FORMAT)

    for vertex in mesh.vertices:
        for value in vertex:
            out += f32(value)

    return bytes(out)


def encode_indx_group(mesh: S3dMesh) -> bytes:
    out = bytearray()

    out += u16(0)
    out += u16(INDX_STRIDE)
    out += u16(len(mesh.indices))

    for index in mesh.indices:
        out += u16(index)

    return bytes(out)


def encode_prim_group(num_indices: int) -> bytes:
    """
    One Triangle primitive spanning the entire index group.
    """
    return (
        u16(1)
        + u32(PRIM_TRIANGLE)
        + u32(0)
        + u32(num_indices)
    )


def encode_mats_group(mesh: S3dMesh) -> bytes:
    flags = (
        MATS_ALPHA_TEST
        | MATS_DEPTH_TEST
        | MATS_BACKFACE_CULLING
        | MATS_TEXTURING
    )

    out = bytearray()

    out += u32(flags)

    out += bytes(
        (
            MATS_FUNC_GREATER,
            MATS_FUNC_LESS_EQUAL,
            MATS_BLEND_ONE,
            MATS_BLEND_ZERO,
        )
    )

    out += i16(0x7FFF)
    out += u32(0)
    out += b"\x00"

    # Number of material records.
    out += b"\x01"

    out += u32(mesh.material_iid)

    out += bytes(
        (
            WRAP_REPEAT,
            WRAP_REPEAT,
            MAG_NEAREST,
            MIN_NEAREST_NO_MIPMAP,
        )
    )

    out += i16(0)
    out += i16(0)

    out += named_string(
        mesh.material_name,
        short=False,
    )

    return bytes(out)


def encode_anim_group(
    mesh_index: int,
    prim_index: int,
    name: str | None,
) -> bytes:
    out = bytearray()

    out += named_string(
        name,
        short=True,
    )

    out += u16(mesh_index)
    out += u16(mesh_index)
    out += u16(prim_index)
    out += u16(mesh_index)

    return bytes(out)


def generic_section(
    signature: bytes,
    groups: Sequence[bytes],
) -> bytes:
    body = (
        u32(len(groups))
        + b"".join(groups)
    )

    return (
        signature
        + u32(8 + len(body))
        + body
    )


def encode_s3d(
    obj_path: Path,
    iid: int,
) -> bytes:
    """
    Convert one restricted BAT OBJ file to S3D v1.5.
    """
    model = parse_obj(obj_path)
    meshes = convert_obj_meshes(
        model,
        iid,
    )

    vert_groups = [
        encode_vert_group(mesh)
        for mesh in meshes
    ]

    indx_groups = [
        encode_indx_group(mesh)
        for mesh in meshes
    ]

    mats_groups = [
        encode_mats_group(mesh)
        for mesh in meshes
    ]

    # PRIM groups can be shared when index counts match.
    prim_sizes: list[int] = []
    prim_index_by_size: dict[int, int] = {}

    for mesh in meshes:
        size = len(mesh.indices)

        if size not in prim_index_by_size:
            prim_index_by_size[size] = len(prim_sizes)
            prim_sizes.append(size)

    prim_groups = [
        encode_prim_group(size)
        for size in prim_sizes
    ]

    anim_groups = [
        encode_anim_group(
            mesh_index=index,
            prim_index=prim_index_by_size[
                len(mesh.indices)
            ],
            name=mesh.name,
        )
        for index, mesh in enumerate(meshes)
    ]

    head = (
        b"HEAD"
        + u32(12)
        + u16(1)
        + u16(5)
    )

    vert = generic_section(
        b"VERT",
        vert_groups,
    )

    indx = generic_section(
        b"INDX",
        indx_groups,
    )

    prim = generic_section(
        b"PRIM",
        prim_groups,
    )

    mats = generic_section(
        b"MATS",
        mats_groups,
    )

    anim_body = bytearray()

    anim_body += u16(1)
    anim_body += u16(0)
    anim_body += u16(PLAYMODE_LOOPING)
    anim_body += u32(0)
    anim_body += f32(0)
    anim_body += u16(len(anim_groups))
    anim_body += b"".join(anim_groups)

    anim = (
        b"ANIM"
        + u32(8 + len(anim_body))
        + bytes(anim_body)
    )

    prop = generic_section(
        b"PROP",
        [],
    )

    regp = generic_section(
        b"REGP",
        [],
    )

    body = (
        head
        + vert
        + indx
        + prim
        + mats
        + anim
        + prop
        + regp
    )

    return (
        b"3DMD"
        + u32(8 + len(body))
        + body
    )


# ---------------------------------------------------------------------------
# Minimal DXT1 encoder
# ---------------------------------------------------------------------------

def rgb_to_565(
    red: int,
    green: int,
    blue: int,
) -> int:
    r5 = (red * 31 + 127) // 255
    g6 = (green * 63 + 127) // 255
    b5 = (blue * 31 + 127) // 255

    return (
        (r5 << 11)
        | (g6 << 5)
        | b5
    )


def rgb_from_565(
    value: int,
) -> tuple[int, int, int]:
    r5 = (value >> 11) & 31
    g6 = (value >> 5) & 63
    b5 = value & 31

    return (
        (r5 << 3) | (r5 >> 2),
        (g6 << 2) | (g6 >> 4),
        (b5 << 3) | (b5 >> 2),
    )


def color_distance_sq(
    a: tuple[int, int, int],
    b: tuple[int, int, int],
) -> int:
    dr = a[0] - b[0]
    dg = a[1] - b[1]
    db = a[2] - b[2]

    return (
        dr * dr
        + dg * dg
        + db * db
    )


def choose_block_endpoints(
    colors: list[tuple[int, int, int, int]],
) -> tuple[int, int]:
    """
    Small dependency-free endpoint approximation.

    This is intentionally simpler than jsquish. It is meant to prove the
    Python-only pipeline, not to match fshgen's DXT compressor byte-for-byte.
    """
    opaque = [
        (red, green, blue)
        for red, green, blue, alpha in colors
        if alpha >= 128
    ]

    if not opaque:
        return 0, 0

    candidates: set[
        tuple[int, int, int]
    ] = set()

    for channel in range(3):
        candidates.add(
            min(
                opaque,
                key=lambda color: color[channel],
            )
        )

        candidates.add(
            max(
                opaque,
                key=lambda color: color[channel],
            )
        )

    candidate_list = list(candidates)

    best_a = candidate_list[0]
    best_b = candidate_list[0]
    best_distance = -1

    for color_a in candidate_list:
        for color_b in candidate_list:
            distance = color_distance_sq(
                color_a,
                color_b,
            )

            if distance > best_distance:
                best_a = color_a
                best_b = color_b
                best_distance = distance

    return (
        rgb_to_565(*best_a),
        rgb_to_565(*best_b),
    )


def dxt1_palette(
    color0: int,
    color1: int,
) -> list[tuple[int, int, int, int]]:
    rgb0 = rgb_from_565(color0)
    rgb1 = rgb_from_565(color1)

    if color0 > color1:
        return [
            (*rgb0, 255),
            (*rgb1, 255),
            (
                (2 * rgb0[0] + rgb1[0]) // 3,
                (2 * rgb0[1] + rgb1[1]) // 3,
                (2 * rgb0[2] + rgb1[2]) // 3,
                255,
            ),
            (
                (rgb0[0] + 2 * rgb1[0]) // 3,
                (rgb0[1] + 2 * rgb1[1]) // 3,
                (rgb0[2] + 2 * rgb1[2]) // 3,
                255,
            ),
        ]

    return [
        (*rgb0, 255),
        (*rgb1, 255),
        (
            (rgb0[0] + rgb1[0]) // 2,
            (rgb0[1] + rgb1[1]) // 2,
            (rgb0[2] + rgb1[2]) // 2,
            255,
        ),
        (0, 0, 0, 0),
    ]


def encode_dxt1_block(
    colors: list[tuple[int, int, int, int]],
) -> bytes:
    has_transparency = any(
        alpha < 128
        for _, _, _, alpha in colors
    )

    color0, color1 = choose_block_endpoints(
        colors
    )

    if has_transparency:
        # DXT1 1-bit-alpha mode.
        if color0 > color1:
            color0, color1 = color1, color0

    else:
        # DXT1 opaque four-color mode.
        if color0 < color1:
            color0, color1 = color1, color0

        elif color0 == color1:
            if color0 < 0xFFFF:
                color0 += 1

            elif color1 > 0:
                color1 -= 1

    palette = dxt1_palette(
        color0,
        color1,
    )

    packed_indices = 0

    for pixel_index, (
        red,
        green,
        blue,
        alpha,
    ) in enumerate(colors):

        if (
            has_transparency
            and alpha < 128
        ):
            palette_index = 3

        else:
            choices = (
                range(3)
                if color0 <= color1
                else range(4)
            )

            palette_index = min(
                choices,
                key=lambda idx: color_distance_sq(
                    (red, green, blue),
                    palette[idx][:3],
                ),
            )

        packed_indices |= (
            (palette_index & 3)
            << (2 * pixel_index)
        )

    return (
        u16(color0)
        + u16(color1)
        + u32(packed_indices)
    )


def encode_dxt1(
    image: Image.Image,
) -> bytes:
    image = image.convert("RGBA")
    width, height = image.size

    if width % 4 or height % 4:
        raise ValueError(
            "DXT1 requires width and height divisible by 4; "
            f"got {width}x{height}"
        )

    pixels = image.load()
    out = bytearray()

    for block_y in range(
        0,
        height,
        4,
    ):
        for block_x in range(
            0,
            width,
            4,
        ):
            block = [
                pixels[
                    block_x + x,
                    block_y + y,
                ]
                for y in range(4)
                for x in range(4)
            ]

            out += encode_dxt1_block(
                block
            )

    return bytes(out)


# ---------------------------------------------------------------------------
# PNG/BMP -> FSH
# ---------------------------------------------------------------------------

def encode_fsh_dxt1(
    image_path: Path,
) -> bytes:
    image = Image.open(
        image_path
    ).convert("RGBA")

    width, height = image.size

    dxt_data = encode_dxt1(
        image
    )

    element_size = (
        0x10
        + len(dxt_data)
    )

    element_offset = 0x18

    total_size = (
        0x10
        + 8
        + element_size
    )

    out = bytearray()

    out += b"SHPI"
    out += u32(total_size)
    out += u32(1)

    # fshgen default directory ID is G264.
    out += b"G264"

    out += b"BMP1"
    out += u32(element_offset)

    # High 24 bits contain element size.
    # Low byte 0x60 is DXT1.
    out += u32(
        (element_size << 8)
        | 0x60
    )

    out += u16(width)
    out += u16(height)

    out += u16(0)
    out += u16(0)
    out += u16(0)
    out += u16(0)

    out += dxt_data

    if len(out) != total_size:
        raise AssertionError(
            (
                len(out),
                total_size,
            )
        )

    return bytes(out)



# ---------------------------------------------------------------------------
# QFS / RefPack compression
# ---------------------------------------------------------------------------

def _highest_one_bit(value: int) -> int:
    if value <= 0:
        return 0
    return 1 << (value.bit_length() - 1)


class _QfsHash:
    """
    Hash-chain match finder corresponding to the compact QFS compressor used by
    scdbpf. The encoded stream format is the standard Maxis QFS/RefPack format
    used by SimCity 4 DBPF resources.
    """

    LOOK_AHEAD = 3

    def __init__(self, size_hint: int):
        self.window_size = min(
            0x20000,
            _highest_one_bit(size_hint),
        )
        self.window_mask = self.window_size - 1

        self.hash_size = min(
            0x10000,
            max(
                0x20,
                _highest_one_bit(size_hint) // 2,
            ),
        )
        self.hash_mask = self.hash_size - 1

        trailing_zeros = (
            self.hash_size.bit_length() - 1
        )
        self.hash_shift = (
            trailing_zeros + self.LOOK_AHEAD - 1
        ) // self.LOOK_AHEAD

        self.value = 0
        self.previous_positions = [0] * self.window_size
        self.head = [-1] * self.hash_size

    def update(self, byte_value: int) -> None:
        self.value = (
            (self.value << self.hash_shift)
            ^ (byte_value & 0xFF)
        ) & self.hash_mask

    def insert(self, position: int) -> None:
        slot = position & self.window_mask
        self.previous_positions[slot] = self.head[self.value]
        self.head[self.value] = position

    def previous(self, position: int) -> int:
        return self.previous_positions[
            position & self.window_mask
        ]


def qfs_is_compressed(data: bytes) -> bool:
    if len(data) < 9:
        return False

    magic = struct.unpack_from("<H", data, 4)[0]
    if magic != QFS_MAGIC:
        return False

    # Avoid treating an S3D whose bytes happen to match the QFS signature as
    # compressed, mirroring scdbpf's safeguard.
    return data[:4] != b"3DMD"


def qfs_decompressed_size(data: bytes) -> int | None:
    if not qfs_is_compressed(data):
        return None

    return (
        (data[6] << 16)
        | (data[7] << 8)
        | data[8]
    )


def qfs_decompress(data: bytes) -> bytes:
    """
    Small verifier/decompressor used by this prototype for self-checking the
    streams emitted by qfs_compress_raw().
    """
    expected = qfs_decompressed_size(data)
    if expected is None:
        return data

    src = 9
    out = bytearray()

    while src < len(data):
        control = data[src]
        src += 1

        if control >= 0xFC:
            plain = control & 0x03
            out += data[src:src + plain]
            src += plain
            break

        if control >= 0xE0:
            plain = ((control & 0x1F) << 2) + 4
            out += data[src:src + plain]
            src += plain
            continue

        if control >= 0xC0:
            if src + 3 > len(data):
                raise ValueError("truncated QFS 4-byte command")

            b1 = data[src]
            b2 = data[src + 1]
            b3 = data[src + 2]
            src += 3

            plain = control & 0x03
            copy_length = (
                ((control & 0x0C) << 6)
                + b3
                + 5
            )
            copy_offset = (
                ((control & 0x10) << 12)
                + (b1 << 8)
                + b2
            )

        elif control >= 0x80:
            if src + 2 > len(data):
                raise ValueError("truncated QFS 3-byte command")

            b1 = data[src]
            b2 = data[src + 1]
            src += 2

            plain = b1 >> 6
            copy_length = (
                (control & 0x3F)
                + 4
            )
            copy_offset = (
                ((b1 & 0x3F) << 8)
                + b2
            )

        else:
            if src >= len(data):
                raise ValueError("truncated QFS 2-byte command")

            b1 = data[src]
            src += 1

            plain = control & 0x03
            copy_length = (
                ((control >> 2) & 0x07)
                + 3
            )
            copy_offset = (
                ((control & 0x60) << 3)
                + b1
            )

        out += data[src:src + plain]
        src += plain

        copy_pos = (
            len(out)
            - copy_offset
            - 1
        )

        if copy_pos < 0:
            raise ValueError("invalid QFS copy offset")

        # QFS matches may overlap, so copy byte-by-byte.
        for _ in range(copy_length):
            out.append(out[copy_pos])
            copy_pos += 1

    if len(out) != expected:
        raise ValueError(
            "QFS decompression size mismatch: "
            f"expected {expected}, got {len(out)}"
        )

    return bytes(out)


def qfs_compress_raw(data: bytes) -> bytes:
    """
    Encode one QFS/RefPack stream.

    This is a Python port of the command selection used by memo33/scdbpf's
    QfsCompression implementation. It searches a 0x20000-byte maximum sliding
    window, supports matches from 3 to 1028 bytes, and limits hash-chain scans
    to 0x80 candidates.
    """
    source = bytes(data)
    source_size = len(source)

    if not (
        9 < source_size <= 0xFFFFFF
    ):
        return source

    LOOK_AHEAD = 3
    MIN_MATCH = 3
    MAX_MATCH = 1028
    MAX_ITER = 0x80

    finder = _QfsHash(source_size)
    max_distance = finder.window_size

    # Nine-byte header is filled after encoding.
    dest = bytearray(b"\x00" * 9)

    src_pos = 0

    finder.update(source[0])
    finder.update(source[1])
    finder.update(source[2])
    finder.insert(src_pos)

    def hash_update(position: int) -> None:
        finder.update(
            source[
                position + LOOK_AHEAD - 1
            ]
        )
        finder.insert(position)

    def common_prefix(
        match_pos: int,
        current_pos: int,
    ) -> int:
        length = 0
        max_length = min(
            MAX_MATCH,
            source_size - current_pos,
        )

        while (
            length < max_length
            and source[match_pos + length]
            == source[current_pos + length]
        ):
            length += 1

        return length

    def has_codepoint(
        offset: int,
        length: int,
    ) -> bool:
        return (
            (length >= 3 and offset < 1024)
            or (length >= 4 and offset < 0x4000)
            or (length >= 5 and offset < 0x20000)
        )

    def find_match(
        current_pos: int,
    ) -> tuple[int, int]:
        match_pos = finder.previous(current_pos)

        best_length = 0
        best_position = current_pos
        iteration = 0

        while (
            iteration <= MAX_ITER
            and match_pos >= 0
            and current_pos - match_pos <= max_distance
            and best_length < MAX_MATCH
            and current_pos + best_length < source_size
        ):
            if (
                best_length < 2
                or (
                    match_pos + best_length < current_pos
                    and source[match_pos + best_length]
                    == source[current_pos + best_length]
                    and source[match_pos + best_length - 1]
                    == source[current_pos + best_length - 1]
                )
                or (
                    match_pos + best_length >= current_pos
                    and source[match_pos + best_length]
                    == source[current_pos + best_length]
                    and source[match_pos + best_length - 1]
                    == source[current_pos + best_length - 1]
                )
            ):
                length = common_prefix(
                    match_pos,
                    current_pos,
                )
            else:
                length = 0

            offset = (
                current_pos
                - match_pos
                - 1
            )

            if (
                length > best_length
                and has_codepoint(
                    offset,
                    length,
                )
            ):
                best_length = min(
                    length,
                    MAX_MATCH,
                )
                best_position = match_pos

            match_pos = finder.previous(
                match_pos
            )
            iteration += 1

        return best_length, best_position

    def transfer_plain(
        start: int,
        length: int,
    ) -> None:
        if length > 0:
            dest.extend(
                source[start:start + length]
            )

    def encode(
        plain_length: int,
        copy_length: int,
        current_pos: int,
        match_position: int,
    ) -> None:
        """
        Encode pending literal bytes followed by an optional back-reference.
        """
        remaining_plain = plain_length

        while remaining_plain >= 4:
            chunk = min(
                remaining_plain & ~0x03,
                112,
            )

            dest.append(
                (chunk // 4) + 0xDF
            )

            start = (
                current_pos
                - remaining_plain
            )

            transfer_plain(
                start,
                chunk,
            )

            remaining_plain -= chunk

        if copy_length == 0:
            dest.append(
                0xFC + remaining_plain
            )

            if remaining_plain:
                start = (
                    current_pos
                    - remaining_plain
                )
                transfer_plain(
                    start,
                    remaining_plain,
                )

            return

        offset = (
            current_pos
            - match_position
            - 1
        )

        if (
            offset < 1024
            and 3 <= copy_length <= 10
        ):
            dest.append(
                ((offset >> 3) & 0x60)
                + ((copy_length - 3) * 4)
                + remaining_plain
            )
            dest.append(
                offset & 0xFF
            )

        elif (
            offset < 0x4000
            and 4 <= copy_length <= 67
        ):
            dest.append(
                0x80
                + (copy_length - 4)
            )
            dest.append(
                remaining_plain * 0x40
                + (offset >> 8)
            )
            dest.append(
                offset & 0xFF
            )

        elif (
            offset < 0x20000
            and 5 <= copy_length <= 1028
        ):
            dest.append(
                0xC0
                + ((offset >> 12) & 0x10)
                + (((copy_length - 5) >> 6) & 0x0C)
                + remaining_plain
            )
            dest.append(
                (offset >> 8) & 0xFF
            )
            dest.append(
                offset & 0xFF
            )
            dest.append(
                (copy_length - 5) & 0xFF
            )

        else:
            raise AssertionError(
                "no suitable QFS code point: "
                f"offset={offset}, "
                f"copy_length={copy_length}, "
                f"plain_length={remaining_plain}"
            )

        if remaining_plain:
            start = (
                current_pos
                - remaining_plain
            )
            transfer_plain(
                start,
                remaining_plain,
            )

    plain_start = src_pos

    while True:
        remaining = (
            source_size
            - src_pos
        )

        if remaining <= 3:
            src_pos = source_size

            encode(
                src_pos - plain_start,
                0,
                src_pos,
                src_pos,
            )
            break

        copy_length, match_position = find_match(
            src_pos
        )

        if copy_length < MIN_MATCH:
            src_pos += 1
            hash_update(src_pos)
            continue

        encode(
            src_pos - plain_start,
            copy_length,
            src_pos,
            match_position,
        )

        for _ in range(copy_length):
            src_pos += 1

            if (
                source_size - src_pos
                >= LOOK_AHEAD
            ):
                hash_update(src_pos)

        plain_start = src_pos

    compressed_size = len(dest)

    struct.pack_into(
        "<I",
        dest,
        0,
        compressed_size,
    )
    struct.pack_into(
        "<H",
        dest,
        4,
        QFS_MAGIC,
    )

    dest[6] = (
        source_size >> 16
    ) & 0xFF
    dest[7] = (
        source_size >> 8
    ) & 0xFF
    dest[8] = (
        source_size
    ) & 0xFF

    result = bytes(dest)

    # Verify our encoder before allowing the stream into a DBPF.
    if qfs_decompress(result) != source:
        raise AssertionError(
            "internal QFS round-trip verification failed"
        )

    return result


def qfs_compress(data: bytes) -> bytes:
    """
    Compress only when worthwhile.

    scdbpf requires the compressed stream to save more than 16 bytes, because
    every compressed DBPF entry adds a 16-byte row to the DIR resource.
    """
    source = bytes(data)

    if (
        len(source) <= 9
        or len(source) > 0xFFFFFF
        or qfs_is_compressed(source)
    ):
        return source

    compressed = qfs_compress_raw(
        source
    )

    if (
        compressed is not source
        and len(compressed)
        < len(source) - 16
    ):
        return compressed

    return source


def build_dir_resource(
    compressed_entries: Sequence["DbpfEntry"],
) -> bytes:
    """
    Build the SC4 DBPF DIR payload.

    Each record is:
        TID, GID, IID, decompressed_size
    as four little-endian uint32 values.
    """
    out = bytearray()

    for entry in compressed_entries:
        if entry.decompressed_size is None:
            continue

        out += struct.pack(
            "<IIII",
            entry.tid & 0xFFFFFFFF,
            entry.gid & 0xFFFFFFFF,
            entry.iid & 0xFFFFFFFF,
            entry.decompressed_size & 0xFFFFFFFF,
        )

    return bytes(out)



# ---------------------------------------------------------------------------
# DBPF writer
# ---------------------------------------------------------------------------

@dataclass
class DbpfEntry:
    tid: int
    gid: int
    iid: int
    data: bytes
    decompressed_size: int | None = None


def write_dbpf(
    path: Path,
    entries: Sequence[DbpfEntry],
) -> None:
    """
    Write DBPF 1.0 with QFS compression where useful.

    Compressed resources are listed in one standard DIR resource:
      E86B1EEF / E86B1EEF / 286B1F03

    The DIR resource itself is stored uncompressed.
    """
    packed_entries: list[DbpfEntry] = []

    for entry in entries:
        raw = bytes(entry.data)
        packed = qfs_compress(raw)

        if packed != raw:
            packed_entries.append(
                DbpfEntry(
                    tid=entry.tid,
                    gid=entry.gid,
                    iid=entry.iid,
                    data=packed,
                    decompressed_size=len(raw),
                )
            )
        else:
            packed_entries.append(
                DbpfEntry(
                    tid=entry.tid,
                    gid=entry.gid,
                    iid=entry.iid,
                    data=raw,
                    decompressed_size=None,
                )
            )

    compressed_entries = [
        entry
        for entry in packed_entries
        if entry.decompressed_size is not None
    ]

    if compressed_entries:
        packed_entries.append(
            DbpfEntry(
                tid=TID_DIR,
                gid=GID_DIR,
                iid=IID_DIR,
                data=build_dir_resource(
                    compressed_entries
                ),
                decompressed_size=None,
            )
        )

    # Keep deterministic ordering, including the DIR entry.
    packed_entries.sort(
        key=lambda entry: (
            entry.tid,
            entry.gid,
            entry.iid,
        )
    )

    header = bytearray(96)
    header[0:4] = b"DBPF"

    struct.pack_into("<I", header, 4, 1)
    struct.pack_into("<I", header, 8, 0)

    now = int(time.time()) & 0xFFFFFFFF
    struct.pack_into("<I", header, 24, now)
    struct.pack_into("<I", header, 28, now)

    struct.pack_into("<I", header, 32, 7)

    payload = bytearray()
    index = bytearray()
    cursor = 96

    for entry in packed_entries:
        data = bytes(entry.data)

        index += struct.pack(
            "<IIIII",
            entry.tid & 0xFFFFFFFF,
            entry.gid & 0xFFFFFFFF,
            entry.iid & 0xFFFFFFFF,
            cursor,
            len(data),
        )

        payload += data
        cursor += len(data)

    index_offset = 96 + len(payload)

    struct.pack_into(
        "<I",
        header,
        36,
        len(packed_entries),
    )
    struct.pack_into(
        "<I",
        header,
        40,
        index_offset,
    )
    struct.pack_into(
        "<I",
        header,
        44,
        len(index),
    )

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    path.write_bytes(
        bytes(header)
        + bytes(payload)
        + bytes(index)
    )

    raw_total = sum(
        len(entry.data)
        if entry.decompressed_size is None
        else entry.decompressed_size
        for entry in packed_entries
        if entry.tid != TID_DIR
    )

    stored_total = sum(
        len(entry.data)
        for entry in packed_entries
        if entry.tid != TID_DIR
    )

    print(
        f"QFS: {len(compressed_entries)} compressed entries; "
        f"resource bytes {raw_total:,} -> {stored_total:,}"
    )


# ---------------------------------------------------------------------------
# Import command
# ---------------------------------------------------------------------------

def import_files(
    output: Path,
    gid: int,
    input_paths: Sequence[Path],
    *,
    force: bool,
    with_bat_models: bool,
    image_format: str,
) -> None:
    if image_format.lower() != "dxt1":
        raise ValueError(
            "mini_fshgen currently supports only --format Dxt1"
        )

    if (
        output.exists()
        and not force
    ):
        raise FileExistsError(
            f"output already exists; use --force: {output}"
        )

    entries: list[DbpfEntry] = []

    for path in input_paths:
        if not path.is_file():
            print(
                f"File {path} does not exist and has been skipped",
                file=sys.stderr,
            )
            continue

        suffix = path.suffix.lower()

        iid = extract_last_iid(
            path.name
        )

        if suffix == ".obj":
            if not with_bat_models:
                print(
                    f"warning: OBJ skipped without --with-BAT-models: {path}",
                    file=sys.stderr,
                )
                continue

            print(
                f"OBJ -> S3D  IID=0x{iid:08X}: {path}"
            )

            entries.append(
                DbpfEntry(
                    tid=TID_S3D,
                    gid=gid,
                    iid=iid,
                    data=encode_s3d(
                        path,
                        iid,
                    ),
                )
            )

        elif suffix in (
            ".png",
            ".bmp",
        ):
            print(
                f"image -> FSH IID=0x{iid:08X}: {path}"
            )

            entries.append(
                DbpfEntry(
                    tid=TID_FSH,
                    gid=gid,
                    iid=iid,
                    data=encode_fsh_dxt1(
                        path
                    ),
                )
            )

        elif (
            suffix == ".mtl"
            and with_bat_models
        ):
            continue

        else:
            print(
                f"warning: unsupported input skipped: {path}",
                file=sys.stderr,
            )

    if not entries:
        raise RuntimeError(
            "no supported input files were converted"
        )

    entries.sort(
        key=lambda entry: (
            entry.tid,
            entry.gid,
            entry.iid,
        )
    )

    write_dbpf(
        output,
        entries,
    )

    print(
        f"Wrote {output} with "
        f"{len(entries)} source DBPF entries."
    )


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_gid(text: str) -> int:
    value = text.strip().lower()

    if value.startswith("0x"):
        value = value[2:]

    if (
        not value
        or len(value) > 8
        or any(
            char not in "0123456789abcdef"
            for char in value
        )
    ):
        raise ValueError(
            f"invalid 32-bit GID: {text}"
        )

    return int(
        value,
        16,
    )


def make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Experimental Python-only BAT subset "
            "of memo33/fshgen"
        )
    )

    subparsers = parser.add_subparsers(
        dest="command",
        required=True,
    )

    importer = subparsers.add_parser(
        "import",
        help=(
            "convert BAT OBJ/PNG files into "
            "a DBPF/SC4Model"
        ),
    )

    importer.add_argument(
        "-o",
        "--output",
        type=Path,
        required=True,
    )

    importer.add_argument(
        "-f",
        "--force",
        action="store_true",
    )

    importer.add_argument(
        "--with-BAT-models",
        dest="with_bat_models",
        action="store_true",
    )

    importer.add_argument(
        "--format",
        default="Dxt1",
    )

    importer.add_argument(
        "--gid",
        required=True,
    )

    importer.add_argument(
        "inputs",
        nargs="+",
    )

    return parser


def main(
    argv: Sequence[str] | None = None,
) -> int:
    parser = make_parser()
    args = parser.parse_args(argv)

    try:
        if args.command == "import":
            gid = parse_gid(
                args.gid
            )

            inputs = expand_inputs(
                args.inputs
            )

            import_files(
                output=args.output,
                gid=gid,
                input_paths=inputs,
                force=args.force,
                with_bat_models=args.with_bat_models,
                image_format=args.format,
            )

            return 0

        parser.error(
            f"unknown command: {args.command}"
        )

    except Exception as exc:
        print(
            f"mini_fshgen: error: {exc}",
            file=sys.stderr,
        )
        return 1

    return 2


if __name__ == "__main__":
    raise SystemExit(
        main()
    )
